name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APKs
        run: flutter build apk --split-per-abi

      - name: Upload APKs
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: build/app/outputs/flutter-apk/

